import { ThemeProvider } from '@/components/providers/theme-provider';
import type { Metadata } from 'next';
import { Bricolage_Grotesque, Raleway } from 'next/font/google';
import './globals.css';

const bricolageGrotesque = Bricolage_Grotesque({
	subsets: ['latin'],
	variable: '--font-bricolageGrotesque',
});
const raleway = Raleway({
	subsets: ['latin'],
	variable: '--font-raleway',
});

export const metadata: Metadata = {
	title: 'Ecoseed',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${raleway.variable} ${bricolageGrotesque.variable}`}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
					storageKey='ecoseed-theme'
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
